---
# tasks file for nginx

- name: Install nginx
  apt: name=nginx update_cache=yes cache_valid_time=86400

- name: copy nginx config files
  template: src={{ item }} dest=/etc/nginx/conf.d/{{ (item | basename | splitext)[0] }}
  with_items: "{{ nginx_config_templates }}"
  notify: nginx_config_changed

- name: copy nginx sites config
  when: nginx_sites_template != ''
  template: src={{ nginx_sites_template }} dest=/etc/nginx/sites-available/default
  notify: nginx_config_changed

- name: copy index.html
  when: nginx_index_html != ''
  template: src={{ nginx_index_html }} dest=/usr/share/nginx/html/index.html mode=0644
