---
# tasks file for nginx

- block:
    - name: Install nginx
      apt: name=nginx update_cache=no

    - name: create directories for ssl certificates
      file: path=/etc/nginx/ssl state=directory

    - name: copy TLS key
      copy: src=files/{{ item }} dest=/etc/nginx/ssl/{{ item }} owner=root mode=0600
      with_items:
        - nginx.key
        - nginx.crt
      notify: ssl_certs_changed

    - name: copy nginx config files
      template: src={{ item }} dest=/etc/nginx/conf.d/{{ (item | basename | splitext)[0] }}
      with_items: "{{ nginx_config_templates }}"
      notify: nginx_config_changed

    - name: copy nginx sites config
      when: nginx_sites_template != ''
      template: src={{ nginx_sites_template }} dest=/etc/nginx/sites-available/default
      notify: nginx_config_changed

  become: true
  become_user: root

