---
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true  # avoid building an image from Dockerfile.j2
provisioner:
  name: ansible
  playbooks: prepare-docker-in-docker.yml
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - destroy
