#!/usr/bin/env ansible-playbook

# call '/bin/sh date', assign the output to a fact and print the result

---
- name: Get date
  hosts: all
  tasks:
    - name: print undefined date
      debug: var=date

    - name: execute date
      shell: >
        date
      register: date_result

    - name: assign result to 'date'
      set_fact: date={{ date_result.stdout }}

    - name: print defined date
      debug: var=date