#!/usr/bin/env ansible-playbook
---
- name: install the hello-world service
  hosts: nginx
  tasks:

    - name: install apt packages
      apt: pkg=python-pip update_cache=yes cache_valid_time=86400
      become: True

    - name: Install python libraries
      pip: name={{ item }}
      become: True
      with_items:
        - Flask
      # should be based on a dependency file

    - name: deploy hello-world service
      copy: src=hello-world dest=~ owner=vagrant mode=0700

    - name: run hello-world service
      shell: ~/hello-world/run.sh
      register: run_result
      changed_when: run_result.stdout != "already running"
