#!/usr/bin/env ansible-playbook
---
- name: Configure webserver with nginx and tls
  hosts: nginx
  become: True

  vars:

  pre_tasks:
    - debug: msg="running pre-tasks"

  roles:
    - role: hello-world
      hello_world_version: 1.1
      hello_world_port: 5005

  tasks:
    - debug: msg="running tasks"

  post_tasks:
    - debug: msg="running post-tasks"

    - debug: msg="updating {{ env_name }} environment"
    #- debug: var=hostvars

    # TODO: create nginx role
    # add filters

    - name: Install nginx
      apt: name=nginx update_cache=yes cache_valid_time=3600

    - name: create directories for ssl certificates
      file: path=/etc/nginx/ssl state=directory

    - name: copy TLS key
      copy: src=nginx/{{ item }} dest=/etc/nginx/ssl/{{ item }} owner=root mode=0600
      with_items:
        - nginx.key
        - nginx.crt
      notify: restart nginx

    - name: copy nginx config file
      copy: src=nginx/nginx.conf dest=/etc/nginx/sites-available/default
      notify: restart nginx

    - name: enable configuration
      file: dest=/etc/nginx/sites-enabled/default src=/etc/nginx/sites-available/default state=link
      notify: restart nginx

    - name: copy index.html
      template: src=www/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted