#!/usr/bin/env ansible-playbook
---
- name: main playbook
  hosts: server1
  become: True

  vars:
    hello_world_port: 5008

  vars_files:

  pre_tasks:
    - debug: msg="updating {{ env_name }} environment"

  roles:
    - role: nginx
      nginx_config_template: nginx/nginx.conf.j2
      index_html_template: nginx/index.html.j2

    - role: hello-world
      hello_world_version: 1.1
      #hello_world_port: defined in vars section

  tasks:

  post_tasks:

  handlers:
