#!/usr/bin/env ansible-playbook
---

- name: gather facts from app-servers
  hosts: app-servers
  tasks: [ ]
  # force gathering ansible_eth1 on application servers, required to define the nginx upstream


- name: install and configure nginx
  hosts: nginx
  vars_files:
    - global_vars.yml
  roles:
    - role: nginx
      nginx_config_templates:
        - nginx/nginx_upstream.conf.j2
      nginx_sites_template: nginx/nginx_sites.conf.j2


- name: install and configure hello-world service
  hosts: app-servers
  vars_files:
    - global_vars.yml
  roles:
    - role: hello-world
      hello_world_version: 1.0
      #hello_world_port: defined in global_vars.yml
