#!/usr/bin/env ansible-playbook
---

- name: install and configure hello-world service
  hosts: app-servers
  roles:
    - role: hello-world
      hello_world_version: 1.0
      #hello_world_port: defined group vars


- name: install and configure nginx
  hosts: reverse-proxy
  roles:
    - role: nginx
      nginx_config_templates: nginx/nginx_upstream.conf.j2
      nginx_sites_template: nginx/nginx_sites.conf.j2

  post_tasks:
    - name: install load_balancer script
      copy: src=nginx/load_balancer dest=/opt/load_balancer mode=0744
      become: true
      become_user: root
